### ISSUE TITLE
The markdown syntax content is not what it claims to be

### ISSUE THREAD

**Issue by asnowfix** [ulybu/rally-ext#20] opened 2015-09-03 17:12 UTC
- Claim: `[FE123: something good somewhere](https://xxx.rallydev.com/path/to/task)`
- Reality: `[FE123](https://xxx.rallydev.com/path/to/task)`

**Comment by ulybu** [comment] 2015-09-14 09:21
Hi,
I'm pretty sure the trailing _`_ doesn't come from the extension
Could you PM or mail me the an example of a non working link/dashboard.. I can't reproduce that bug

**Comment by asnowfix** [comment] 2015-09-14 09:47
The issue is not the leading `\``, but the fact that the clear-text includes the full ticket headline in one (the good) case & only the ticket number in the other (bad) case.

**Comment by ulybu** [comment] 2015-09-14 12:06
yes I understood the issue. I can't reproduce it, could you PM or mail me the an example of a non working link/dashboard?

**Comment by ulybu** [comment] 2015-09-21 08:25
Confirmed. Observed on a grid layout (kanban board)

**Comment by ulybu** [comment] 2015-11-20 23:51
Fixed in 813f10f48d4a6f7c72f3a82ff1967cde7e8a330f

**Closed as completed by ulybu** 2015-11-20 23:51 UTC
Labels: bug

**Comment by asnowfix** [comment] 2015-11-23 10:46
Fixed: thanks :-)
